import { ColorIntroduction } from '~/ts/colors'

const brownList: ColorIntroduction[] = [
  {
    jsName: "brown['50']",
    lessName: '@brown50',
    cssName: '--brown-50',
    scssName: '$brown50',
    color: '#efebe9',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "brown['100']",
    lessName: '@brown100',
    cssName: '--brown-100',
    scssName: '$brown100',
    color: '#d7ccc8',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "brown['200']",
    lessName: '@brown200',
    cssName: '--brown-200',
    scssName: '$brown200',
    color: '#bcaaa4',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "brown['300']",
    lessName: '@brown300',
    cssName: '--brown-300',
    scssName: '$brown300',
    color: '#a1887f',
    textColor: '#fff',
  },
  {
    jsName: "brown['400']",
    lessName: '@brown400',
    cssName: '--brown-400',
    scssName: '$brown400',
    color: '#8d6e63',
    textColor: '#fff',
  },
  {
    jsName: "brown['500']",
    lessName: '@brown500',
    cssName: '--brown-500',
    scssName: '$brown500',
    color: '#795548',
    textColor: '#fff',
  },
  {
    jsName: "brown['600']",
    lessName: '@brown600',
    cssName: '--brown-600',
    scssName: '$brown600',
    color: '#6d4c41',
    textColor: '#fff',
  },
  {
    jsName: "brown['700']",
    lessName: '@brown700',
    cssName: '--brown-700',
    scssName: '$brown700',
    color: '#5d4037',
    textColor: '#fff',
  },
  {
    jsName: "brown['800']",
    lessName: '@brown800',
    cssName: '--brown-800',
    scssName: '$brown800',
    color: '#4e342e',
    textColor: '#fff',
  },
  {
    jsName: "brown['900']",
    lessName: '@brown900',
    cssName: '--brown-900',
    scssName: '$brown900',
    color: '#3e2723',
    textColor: '#fff',
  },
  {
    jsName: "brown['A100']",
    lessName: '@brownA100',
    cssName: '--brown-A100',
    scssName: '$brownA100',
    color: '#d7ccc8',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "brown['A200']",
    lessName: '@brownA200',
    cssName: '--brown-A200',
    scssName: '$brownA200',
    color: '#bcaaa4',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "brown['A400']",
    lessName: '@brownA400',
    cssName: '--brown-A400',
    scssName: '$brownA400',
    color: '#8d6e63',
    textColor: '#fff',
  },
  {
    jsName: "brown['A700']",
    lessName: '@brownA700',
    cssName: '--brown-A700',
    scssName: '$brownA700',
    color: '#5d4037',
    textColor: '#fff',
  },
]

export default brownList
