import { ColorIntroduction } from '~/ts/colors'

const deepOrangeList: ColorIntroduction[] = [
  {
    jsName: "deepOrange['50']",
    lessName: '@deepOrange50',
    cssName: '--deep-orange-50',
    scssName: '$deepOrange50',
    color: '#fbe9e7',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "deepOrange['100']",
    lessName: '@deepOrange100',
    cssName: '--deep-orange-100',
    scssName: '$deepOrange100',
    color: '#ffccbc',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "deepOrange['200']",
    lessName: '@deepOrange200',
    cssName: '--deep-orange-200',
    scssName: '$deepOrange200',
    color: '#ffab91',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "deepOrange['300']",
    lessName: '@deepOrange300',
    cssName: '--deep-orange-300',
    scssName: '$deepOrange300',
    color: '#ff8a65',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "deepOrange['400']",
    lessName: '@deepOrange400',
    cssName: '--deep-orange-400',
    scssName: '$deepOrange400',
    color: '#ff7043',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "deepOrange['500']",
    lessName: '@deepOrange500',
    cssName: '--deep-orange-500',
    scssName: '$deepOrange500',
    color: '#ff5722',
    textColor: '#fff',
  },
  {
    jsName: "deepOrange['600']",
    lessName: '@deepOrange600',
    cssName: '--deep-orange-600',
    scssName: '$deepOrange600',
    color: '#f4511e',
    textColor: '#fff',
  },
  {
    jsName: "deepOrange['700']",
    lessName: '@deepOrange700',
    cssName: '--deep-orange-700',
    scssName: '$deepOrange700',
    color: '#e64a19',
    textColor: '#fff',
  },
  {
    jsName: "deepOrange['800']",
    lessName: '@deepOrange800',
    cssName: '--deep-orange-800',
    scssName: '$deepOrange800',
    color: '#d84315',
    textColor: '#fff',
  },
  {
    jsName: "deepOrange['900']",
    lessName: '@deepOrange900',
    cssName: '--deep-orange-900',
    scssName: '$deepOrange900',
    color: '#bf360c',
    textColor: '#fff',
  },
  {
    jsName: "deepOrange['A100']",
    lessName: '@deepOrangeA100',
    cssName: '--deep-orange-A100',
    scssName: '$deepOrangeA100',
    color: '#ff9e80',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "deepOrange['A200']",
    lessName: '@deepOrangeA200',
    cssName: '--deep-orange-A200',
    scssName: '$deepOrangeA200',
    color: '#ff6e40',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "deepOrange['A400']",
    lessName: '@deepOrangeA400',
    cssName: '--deep-orange-A400',
    scssName: '$deepOrangeA400',
    color: '#ff3d00',
    textColor: '#fff',
  },
  {
    jsName: "deepOrange['A700']",
    lessName: '@deepOrangeA700',
    cssName: '--deep-orange-A700',
    scssName: '$deepOrangeA700',
    color: '#dd2c00',
    textColor: '#fff',
  },
]

export default deepOrangeList
