import { ColorIntroduction } from '~/ts/colors'

const deepPurpleList: ColorIntroduction[] = [
  {
    jsName: "deepPurple['50']",
    lessName: '@deepPurple50',
    cssName: '--deep-purple-50',
    scssName: '$deepPurple50',
    color: '#ede7f6',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "deepPurple['100']",
    lessName: '@deepPurple100',
    cssName: '--deep-purple-100',
    scssName: '$deepPurple100',
    color: '#d1c4e9',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "deepPurple['200']",
    lessName: '@deepPurple200',
    cssName: '--deep-purple-200',
    scssName: '$deepPurple200',
    color: '#b39ddb',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "deepPurple['300']",
    lessName: '@deepPurple300',
    cssName: '--deep-purple-300',
    scssName: '$deepPurple300',
    color: '#9575cd',
    textColor: '#fff',
  },
  {
    jsName: "deepPurple['400']",
    lessName: '@deepPurple400',
    cssName: '--deep-purple-400',
    scssName: '$deepPurple400',
    color: '#7e57c2',
    textColor: '#fff',
  },
  {
    jsName: "deepPurple['500']",
    lessName: '@deepPurple500',
    cssName: '--deep-purple-500',
    scssName: '$deepPurple500',
    color: '#673ab7',
    textColor: '#fff',
  },
  {
    jsName: "deepPurple['600']",
    lessName: '@deepPurple600',
    cssName: '--deep-purple-600',
    scssName: '$deepPurple600',
    color: '#5e35b1',
    textColor: '#fff',
  },
  {
    jsName: "deepPurple['700']",
    lessName: '@deepPurple700',
    cssName: '--deep-purple-700',
    scssName: '$deepPurple700',
    color: '#512da8',
    textColor: '#fff',
  },
  {
    jsName: "deepPurple['800']",
    lessName: '@deepPurple800',
    cssName: '--deep-purple-800',
    scssName: '$deepPurple800',
    color: '#4527a0',
    textColor: '#fff',
  },
  {
    jsName: "deepPurple['900']",
    lessName: '@deepPurple900',
    cssName: '--deep-purple-900',
    scssName: '$deepPurple900',
    color: '#311b92',
    textColor: '#fff',
  },
  {
    jsName: "deepPurple['A100']",
    lessName: '@deepPurpleA100',
    cssName: '--deep-purple-A100',
    scssName: '$deepPurpleA100',
    color: '#b388ff',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "deepPurple['A200']",
    lessName: '@deepPurpleA200',
    cssName: '--deep-purple-A200',
    scssName: '$deepPurpleA200',
    color: '#7c4dff',
    textColor: '#fff',
  },
  {
    jsName: "deepPurple['A400']",
    lessName: '@deepPurpleA400',
    cssName: '--deep-purple-A400',
    scssName: '$deepPurpleA400',
    color: '#651fff',
    textColor: '#fff',
  },
  {
    jsName: "deepPurple['A700']",
    lessName: '@deepPurpleA700',
    cssName: '--deep-purple-A700',
    scssName: '$deepPurpleA700',
    color: '#6200ea',
    textColor: '#fff',
  },
]

export default deepPurpleList
