import { ColorIntroduction } from '~/ts/colors'

const indigoList: ColorIntroduction[] = [
  {
    jsName: "indigo['50']",
    lessName: '@indigo50',
    cssName: '--indigo-50',
    scssName: '$indigo50',
    color: '#e8eaf6',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "indigo['100']",
    lessName: '@indigo100',
    cssName: '--indigo-100',
    scssName: '$indigo100',
    color: '#c5cae9',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "indigo['200']",
    lessName: '@indigo200',
    cssName: '--indigo-200',
    scssName: '$indigo200',
    color: '#9fa8da',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "indigo['300']",
    lessName: '@indigo300',
    cssName: '--indigo-300',
    scssName: '$indigo300',
    color: '#7986cb',
    textColor: '#fff',
  },
  {
    jsName: "indigo['400']",
    lessName: '@indigo400',
    cssName: '--indigo-400',
    scssName: '$indigo400',
    color: '#5c6bc0',
    textColor: '#fff',
  },
  {
    jsName: "indigo['500']",
    lessName: '@indigo500',
    cssName: '--indigo-500',
    scssName: '$indigo500',
    color: '#3f51b5',
    textColor: '#fff',
  },
  {
    jsName: "indigo['600']",
    lessName: '@indigo600',
    cssName: '--indigo-600',
    scssName: '$indigo600',
    color: '#3949ab',
    textColor: '#fff',
  },
  {
    jsName: "indigo['700']",
    lessName: '@indigo700',
    cssName: '--indigo-700',
    scssName: '$indigo700',
    color: '#303f9f',
    textColor: '#fff',
  },
  {
    jsName: "indigo['800']",
    lessName: '@indigo800',
    cssName: '--indigo-800',
    scssName: '$indigo800',
    color: '#283593',
    textColor: '#fff',
  },
  {
    jsName: "indigo['900']",
    lessName: '@indigo900',
    cssName: '--indigo-900',
    scssName: '$indigo900',
    color: '#1a237e',
    textColor: '#fff',
  },
  {
    jsName: "indigo['A100']",
    lessName: '@indigoA100',
    cssName: '--indigo-A100',
    scssName: '$indigoA100',
    color: '#8c9eff',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "indigo['A200']",
    lessName: '@indigoA200',
    cssName: '--indigo-A200',
    scssName: '$indigoA200',
    color: '#536dfe',
    textColor: '#fff',
  },
  {
    jsName: "indigo['A400']",
    lessName: '@indigoA400',
    cssName: '--indigo-A400',
    scssName: '$indigoA400',
    color: '#3d5afe',
    textColor: '#fff',
  },
  {
    jsName: "indigo['A700']",
    lessName: '@indigoA700',
    cssName: '--indigo-A700',
    scssName: '$indigoA700',
    color: '#304ffe',
    textColor: '#fff',
  },
]

export default indigoList
