import { ColorIntroduction } from '~/ts/colors'

const lightBlueList: ColorIntroduction[] = [
  {
    jsName: "lightBlue['50']",
    lessName: '@lightBlue50',
    cssName: '--light-blue-50',
    scssName: '$lightBlue50',
    color: '#e1f5fe',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "lightBlue['100']",
    lessName: '@lightBlue100',
    cssName: '--light-blue-100',
    scssName: '$lightBlue100',
    color: '#b3e5fc',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "lightBlue['200']",
    lessName: '@lightBlue200',
    cssName: '--light-blue-200',
    scssName: '$lightBlue200',
    color: '#81d4fa',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "lightBlue['300']",
    lessName: '@lightBlue300',
    cssName: '--light-blue-300',
    scssName: '$lightBlue300',
    color: '#4fc3f7',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "lightBlue['400']",
    lessName: '@lightBlue400',
    cssName: '--light-blue-400',
    scssName: '$lightBlue400',
    color: '#29b6f6',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "lightBlue['500']",
    lessName: '@lightBlue500',
    cssName: '--light-blue-500',
    scssName: '$lightBlue500',
    color: '#03a9f4',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "lightBlue['600']",
    lessName: '@lightBlue600',
    cssName: '--light-blue-600',
    scssName: '$lightBlue600',
    color: '#039be5',
    textColor: '#fff',
  },
  {
    jsName: "lightBlue['700']",
    lessName: '@lightBlue700',
    cssName: '--light-blue-700',
    scssName: '$lightBlue700',
    color: '#0288d1',
    textColor: '#fff',
  },
  {
    jsName: "lightBlue['800']",
    lessName: '@lightBlue800',
    cssName: '--light-blue-800',
    scssName: '$lightBlue800',
    color: '#0277bd',
    textColor: '#fff',
  },
  {
    jsName: "lightBlue['900']",
    lessName: '@lightBlue900',
    cssName: '--light-blue-900',
    scssName: '$lightBlue900',
    color: '#01579b',
    textColor: '#fff',
  },
  {
    jsName: "lightBlue['A100']",
    lessName: '@lightBlueA100',
    cssName: '--light-blue-A100',
    scssName: '$lightBlueA100',
    color: '#80d8ff',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "lightBlue['A200']",
    lessName: '@lightBlueA200',
    cssName: '--light-blue-A200',
    scssName: '$lightBlueA200',
    color: '#40c4ff',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "lightBlue['A400']",
    lessName: '@lightBlueA400',
    cssName: '--light-blue-A400',
    scssName: '$lightBlueA400',
    color: '#00b0ff',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "lightBlue['A700']",
    lessName: '@lightBlueA700',
    cssName: '--light-blue-A700',
    scssName: '$lightBlueA700',
    color: '#0091ea',
    textColor: '#fff',
  },
]

export default lightBlueList
