import { ColorIntroduction } from '~/ts/colors'

const lightGreenList: ColorIntroduction[] = [
  {
    jsName: "lightGreen['50']",
    lessName: '@lightGreen50',
    cssName: '--light-green-50',
    scssName: '$lightGreen50',
    color: '#f1f8e9',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "lightGreen['100']",
    lessName: '@lightGreen100',
    cssName: '--light-green-100',
    scssName: '$lightGreen100',
    color: '#dcedc8',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "lightGreen['200']",
    lessName: '@lightGreen200',
    cssName: '--light-green-200',
    scssName: '$lightGreen200',
    color: '#c5e1a5',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "lightGreen['300']",
    lessName: '@lightGreen300',
    cssName: '--light-green-300',
    scssName: '$lightGreen300',
    color: '#aed581',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "lightGreen['400']",
    lessName: '@lightGreen400',
    cssName: '--light-green-400',
    scssName: '$lightGreen400',
    color: '#9ccc65',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "lightGreen['500']",
    lessName: '@lightGreen500',
    cssName: '--light-green-500',
    scssName: '$lightGreen500',
    color: '#8bc34a',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "lightGreen['600']",
    lessName: '@lightGreen600',
    cssName: '--light-green-600',
    scssName: '$lightGreen600',
    color: '#7cb342',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "lightGreen['700']",
    lessName: '@lightGreen700',
    cssName: '--light-green-700',
    scssName: '$lightGreen700',
    color: '#689f38',
    textColor: '#fff',
  },
  {
    jsName: "lightGreen['800']",
    lessName: '@lightGreen800',
    cssName: '--light-green-800',
    scssName: '$lightGreen800',
    color: '#558b2f',
    textColor: '#fff',
  },
  {
    jsName: "lightGreen['900']",
    lessName: '@lightGreen900',
    cssName: '--light-green-900',
    scssName: '$lightGreen900',
    color: '#33691e',
    textColor: '#fff',
  },
  {
    jsName: "lightGreen['A100']",
    lessName: '@lightGreenA100',
    cssName: '--light-green-A100',
    scssName: '$lightGreenA100',
    color: '#ccff90',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "lightGreen['A200']",
    lessName: '@lightGreenA200',
    cssName: '--light-green-A200',
    scssName: '$lightGreenA200',
    color: '#b2ff59',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "lightGreen['A400']",
    lessName: '@lightGreenA400',
    cssName: '--light-green-A400',
    scssName: '$lightGreenA400',
    color: '#76ff03',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "lightGreen['A700']",
    lessName: '@lightGreenA700',
    cssName: '--light-green-A700',
    scssName: '$lightGreenA700',
    color: '#64dd17',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
]

export default lightGreenList
