import { ColorIntroduction } from '~/ts/colors';

const pinkList: ColorIntroduction[]  = [
  {
    jsName: "pink[50]",
    cssName: "--pink-50",
    scssName: "$pink50",
    lessName: "@pink50",
    color: "#fce4ec",
    textColor: "rgba(0, 0, 0, 0.87)",
  },
  {
    jsName: "pink[100]",
    cssName: "--pink-100",
    scssName: "$pink100",
    lessName: "@pink100",
    color: "#f8bbd0",
    textColor: "rgba(0, 0, 0, 0.87)",
  },
  {
    jsName: "pink[200]",
    cssName: "--pink-200",
    scssName: "$pink200",
    lessName: "@pink200",
    color: "#f48fb1",
    textColor: "rgba(0, 0, 0, 0.87)",
  },
  {
    jsName: "pink[300]",
    cssName: "--pink-300",
    scssName: "$pink300",
    lessName: "@pink300",
    color: "#f06292",
    textColor: "#fff",
  },
  {
    jsName: "pink[400]",
    cssName: "--pink-400",
    scssName: "$pink400",
    lessName: "@pink400",
    color: "#ec407a",
    textColor: "#fff",
  },
  {
    jsName: "pink[500]",
    cssName: "--pink-500",
    scssName: "$pink500",
    lessName: "@pink500",
    color: "#e91e63",
    textColor: "#fff",
  },
  {
    jsName: "pink[600]",
    cssName: "--pink-600",
    scssName: "$pink600",
    lessName: "@pink600",
    color: "#d81b60",
    textColor: "#fff",
  },
  {
    jsName: "pink[700]",
    cssName: "--pink-700",
    scssName: "$pink700",
    lessName: "@pink700",
    color: "#c2185b",
    textColor: "#fff",
  },
  {
    jsName: "pink[800]",
    cssName: "--pink-800",
    scssName: "$pink800",
    lessName: "@pink800",
    color: "#ad1457",
    textColor: "#fff",
  },
  {
    jsName: "pink[900]",
    cssName: "--pink-900",
    scssName: "$pink900",
    lessName: "@pink900",
    color: "#880e4f",
    textColor: "#fff",
  },
  {
    jsName: "pink['A100']",
    cssName: "--pink-A100",
    scssName: "$pinkA100",
    lessName: "@pinkA100",
    color: "#ff80ab",
    textColor: "rgba(0, 0, 0, 0.87)",
  },
  {
    jsName: "pink['A200']",
    cssName: "--pink-A200",
    scssName: "$pinkA200",
    lessName: "@pinkA200",
    color: "#ff4081",
    textColor: "#fff",
  },
  {
    jsName: "pink['A400']",
    cssName: "--pink-A400",
    scssName: "$pinkA400",
    lessName: "@pinkA400",
    color: "#f50057",
    textColor: "#fff",
  },
  {
    jsName: "pink['A700']",
    cssName: "--pink-A700",
    scssName: "$pinkA700",
    lessName: "@pinkA700",
    color: "#c51162",
    textColor: "#fff",
  },
];

export default pinkList;
