import { ColorIntroduction } from '~/ts/colors'

const purpleList: ColorIntroduction[] = [
  {
    jsName: 'purple[50]',
    cssName: '--purple-50',
    scssName: '$purple50',
    lessName: '@purple50',
    color: '#f3e5f5',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: 'purple[100]',
    cssName: '--purple-100',
    scssName: '$purple100',
    lessName: '@purple100',
    color: '#e1bee7',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: 'purple[200]',
    cssName: '--purple-200',
    scssName: '$purple200',
    lessName: '@purple200',
    color: '#ce93d8',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: 'purple[300]',
    cssName: '--purple-300',
    scssName: '$purple300',
    lessName: '@purple300',
    color: '#ba68c8',
    textColor: '#fff',
  },
  {
    jsName: 'purple[400]',
    cssName: '--purple-400',
    scssName: '$purple400',
    lessName: '@purple400',
    color: '#ab47bc',
    textColor: '#fff',
  },
  {
    jsName: 'purple[500]',
    cssName: '--purple-500',
    scssName: '$purple500',
    lessName: '@purple500',
    color: '#9c27b0',
    textColor: '#fff',
  },
  {
    jsName: 'purple[600]',
    cssName: '--purple-600',
    scssName: '$purple600',
    lessName: '@purple600',
    color: '#8e24aa',
    textColor: '#fff',
  },
  {
    jsName: 'purple[700]',
    cssName: '--purple-700',
    scssName: '$purple700',
    lessName: '@purple700',
    color: '#7b1fa2',
    textColor: '#fff',
  },
  {
    jsName: 'purple[800]',
    cssName: '--purple-800',
    scssName: '$purple800',
    lessName: '@purple800',
    color: '#6a1b9a',
    textColor: '#fff',
  },
  {
    jsName: 'purple[900]',
    cssName: '--purple-900',
    scssName: '$purple900',
    lessName: '@purple900',
    color: '#4a148c',
    textColor: '#fff',
  },
  {
    jsName: "purple['A100']",
    cssName: '--purple-A100',
    scssName: '$purpleA100',
    lessName: '@purpleA100',
    color: '#ea80fc',
    textColor: 'rgba(0, 0, 0, 0.87)',
  },
  {
    jsName: "purple['A200']",
    cssName: '--purple-A200',
    scssName: '$purpleA200',
    lessName: '@purpleA200',
    color: '#e040fb',
    textColor: '#fff',
  },
  {
    jsName: "purple['A400']",
    cssName: '--purple-A400',
    scssName: '$purpleA400',
    lessName: '@purpleA400',
    color: '#d500f9',
    textColor: '#fff',
  },
  {
    jsName: "purple['A700']",
    cssName: '--purple-A700',
    scssName: '$purpleA700',
    lessName: '@purpleA700',
    color: '#aa00ff',
    textColor: '#fff',
  },
]

export default purpleList
